services:
  # --- SEU LARAVEL (JÁ EXISTENTE) ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: agenda
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/app/:cached
      - vendor_cache:/var/www/app/src/vendor
    networks:
      - app
      
  # --- SEU BANCO DE DADOS (JÁ EXISTENTE) ---
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: db_agenda
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - app

  # --- NOVO SERVIÇO: AGENTES PYTHON (ADICIONADO AGORA) ---
  agentes_python:
    build:
      context: ./agentes
      dockerfile: Dockerfile
    container_name: invasores_agentes
    # MUDANÇA: Agora rodamos o server.py, não mais o main.py
    command: python server.py 
    ports:
      - "5000:5000" # Para podermos testar se precisarmos
    volumes:
      - ./agentes:/app
    networks:
      - app
    depends_on:
      - app
    env_file:
      - ./agentes/.env

# --- REDES E VOLUMES ---
networks:
  app:
    driver: bridge

volumes:
  vendor_cache: